"""
Django settings for kiado project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from django.utils.translation import gettext_lazy as _
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-on+3))7&e=6#t*b5%+qkzu71fh3co0k0h@0x!=ql@3y_8xtb&!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False #True 
ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'yourdomain.com']

ALLOWED_HOSTS = ['*']  # Ezt változtasd meg a saját domain-edre vagy IP-címedre

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main_kiado',  # Hozzáadott alkalmazás
    'modeltranslation',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware', 
]

ROOT_URLCONF = 'kiado.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main_kiado.context_processors.cart_item_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'kiado.wsgi.application'
CSRF_FAILURE_VIEW = 'main_kiado.views.csrf_failure'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Statikus fájlok URL-je
STATIC_URL = '/static/'

# Statikus fájlok gyökérkönyvtára
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

STATIC_ROOT = [
    os.path.join(BASE_DIR, "static"),
]


# Statikus fájlok gyűjtésének célhelye
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Média fájlok (feltöltött képek)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Session settings
SESSION_COOKIE_NAME = 'user_sessionid'  # Alapértelmezett session cookie
LOGIN_REDIRECT_URL = 'home'  # Bejelentkezés után átirányítás
LOGOUT_REDIRECT_URL = 'home'  # Kijelentkezés után átirányítás
LOGIN_URL = 'login'  # Bejelentkezési URL

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'hu'  # Magyar nyelv
TIME_ZONE = 'Europe/Budapest'
USE_I18N = True
USE_L10N = True
USE_TZ = True

LANGUAGES = [
    ('en', _('English')),
    ('hu', _('Magyar')),
]

# Fordítási fájlok helye
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
    os.path.join(BASE_DIR, 'main_kiado', 'locale'),
]
MODELTRANSLATION_DEFAULT_LANGUAGE = 'hu'  # Alapértelmezett nyelv