# Generated by Django 5.1.2 on 2024-11-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_kiado', '0003_review_delete_velemény'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='about',
            field=models.TextField(default=''),
        ),
    ]
