# Generated by Django 5.1.2 on 2024-12-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_kiado', '0008_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AlterField(
            model_name='profile',
            name='iranyitoszam',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='keresztnev',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lakcim',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefonszam',
            field=models.CharField(blank=True, default='N/A', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='varos',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vezeteknev',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
