# Generated by Django 5.1.2 on 2024-12-15 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_kiado', '0009_remove_profile_email_alter_profile_iranyitoszam_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='iranyitoszam',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Irányítószám'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='keresztnev',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Keresztnév'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lakcim',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Lakcím'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilkep',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profilkép'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefonszam',
            field=models.CharField(blank=True, default='', help_text='Formátum: +36123456789', max_length=15, verbose_name='Telefonszám'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='varos',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Város'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vezeteknev',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Vezetéknév'),
        ),
    ]
