# Generated by Django 5.1.2 on 2024-12-15 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_kiado', '0011_remove_profile_keresztnev_remove_profile_vezeteknev_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
