# Generated by Django 5.1.2 on 2024-12-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_kiado', '0015_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
    ]
